name: memory_echoes
description: "一个温暖的记忆记录与分享应用"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # 权限管理
  permission_handler: ^11.0.1

  # 状态管理
  flutter_riverpod: ^2.4.9

  # 路由
  go_router: ^12.1.3

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.4.1
  firebase_storage: ^12.1.1
  firebase_ai: ^2.2.1

  # 网络请求
  dio: ^5.4.0

  # 本地存储
  shared_preferences: ^2.2.2

  # JSON序列化
  json_annotation: ^4.8.1

  # Freezed
  freezed_annotation: ^2.4.1

  # 环境变量
  flutter_dotenv: ^5.1.0

  # 语音识别
  speech_to_text: ^6.6.0

  # 分享功能
  share_plus: ^7.2.2

  # 图片缓存
  cached_network_image: ^3.3.0

  # 图片选择
  image_picker: ^1.0.4

  # 录音功能
  record: ^5.0.4

  # 路径获取
  path_provider: ^2.1.2

  # 路径操作
  path: ^1.8.3

  # 日期格式化
  intl: ^0.18.1

  # UI图标
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
