// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYseLt2_Q3Q6ceqLxyv5FxMPa1-gPQE4',
    appId: '1:989984865438:web:f387088e96ed938642cf8f',
    messagingSenderId: '989984865438',
    projectId: 'memory-echoes-206a6',
    authDomain: 'memory-echoes-206a6.firebaseapp.com',
    storageBucket: 'memory-echoes-206a6.firebasestorage.app',
    measurementId: 'G-MFTCTSCXFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7REgZPjuAgg40HeC0SWzKeZBOfTmLOl8',
    appId: '1:989984865438:android:f6628a40d34894b642cf8f',
    messagingSenderId: '989984865438',
    projectId: 'memory-echoes-206a6',
    storageBucket: 'memory-echoes-206a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdwUteEol_SAIzTSAX9rZnYDxvapwWJBY',
    appId: '1:989984865438:ios:982bdee8c142043342cf8f',
    messagingSenderId: '989984865438',
    projectId: 'memory-echoes-206a6',
    storageBucket: 'memory-echoes-206a6.firebasestorage.app',
    iosBundleId: 'com.example.memoryEchoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdwUteEol_SAIzTSAX9rZnYDxvapwWJBY',
    appId: '1:989984865438:ios:982bdee8c142043342cf8f',
    messagingSenderId: '989984865438',
    projectId: 'memory-echoes-206a6',
    storageBucket: 'memory-echoes-206a6.firebasestorage.app',
    iosBundleId: 'com.example.memoryEchoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXYseLt2_Q3Q6ceqLxyv5FxMPa1-gPQE4',
    appId: '1:989984865438:web:60602abeb30f490642cf8f',
    messagingSenderId: '989984865438',
    projectId: 'memory-echoes-206a6',
    authDomain: 'memory-echoes-206a6.firebaseapp.com',
    storageBucket: 'memory-echoes-206a6.firebasestorage.app',
    measurementId: 'G-VDTLRJ67TH',
  );
}
